num1=input("Number1 : ")
num2=input("Number2 : ")
print(num1+ "+" +num2+" = ",int(num1)+int(num2))
print(num1+ "-" +num2+" = ",int(num1)-int(num2))
print(num1+ "*" +num2+" = ",int(num1)*int(num2))
print(num1+ "/" +num2+" = ",int(num1)/int(num2))